spring.application.name=makeMyTrip

server.port=8080

# MongoDB Atlas (Injected via Environment Variables)
spring.mongodb.uri=${SPRING_MONGODB_URI}
spring.mongodb.database=${SPRING_MONGODB_DATABASE}

# Logging
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
logging.level.org.mongodb.driver=INFO