spring.application.name=makeMyTrip

server.port=8080

# MongoDB Atlas (Injected via Environment Variables with local fallbacks for Junit testing)
spring.mongodb.uri=${SPRING_MONGODB_URI:mongodb://localhost:27017/makeMyTrip}
spring.mongodb.database=${SPRING_MONGODB_DATABASE:makeMyTrip}

# Logging
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
logging.level.org.mongodb.driver=INFO